name: Deploy DEV

on:
  push:
    branches:
      - dev
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.MX_TOKEN }}
          ARGS: "-avz --delete --exclude='/public/uploads'"
          REMOTE_PORT: 22
          SOURCE: ./
          REMOTE_HOST: ${{ secrets.MX_HOST }}
          REMOTE_USER: "root"
          TARGET: /html/wwwroot/actions-test/